# kind ile cluster kurulurken kaç tane worker ve control plane kurulaçağını ayarlayabilir.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
# - role: worker
