apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    test: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /servers
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3

---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    #    image: k8s.gcr.io/busybox
    args:
    - /bin/bash
    - -c
    - touch /tmp/healty; sleep 30; rm -rf /tmp/healty; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healty
      initialDelaySeconds: 5
      periodSeconds: 5



---
apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    #çalışıyor
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
