apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: default
type: Opaque
stringData:
  password: P@ssw0rd!

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  namespace: default
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqlvolume
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: mysqlclaim

