apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myqlclaim
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  storageClassName: ""
  selector:
    matchLabels:
      app: mysql
  accessModes:
  - ReadWriteOnce
