apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: hostpathcontainer
    image: ozgurozturknet/k8s:blue
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      #mount edilen volumeler
    volumeMounts:
    #Hangi volume un mount edileceği
    - name: dircreate-vol
      # mount edilecek volume nereye mount edilecek
      mountPath: /dirl
    - name: dircreate-vol
      mountPath: /cache 
    - name: DirectoryOrCreate
      mountPath: /cache/config.cfg
  volumes:
  - name: directory-vol
    hostpath:
      path: /tmp
      type: Directory
  - name: dircreate-vol
    hostpath:
      path: /cache
      type: DirectoryOrCreate
  - name: file-vol
    hostpath:
      path: /cache/config.json
      type: FileOrCreate
