apiVersion: v1
kind: Pod
metadata:
  name: tolerationpod1
  labels:
    env: test
spec:
  containers:
  - name: tolerationcontainer1
    image: ozgurozturknet/k8s
  tolerations:
  - key: "platform"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"



---
apiVersion: v1
kind: Pod
metadata:
  name: tolerationpod2
  labels:
    env: test
spec:
  containers:
  - name: tolerationcontainer2
    image: ozgurozturknet/k8s
  tolerations:
  - key: "platform"
    operator: "Exits"
    effect: "NoSchedule"

