apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: webcontainer
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: sharedvolume
      mountPath: /usr/share/nginx/html

  - name: sidecarcontainer
    image: busybox
    command: ["/bin/bash"]
    args: ["-c", "while true; do wget https://raw.githubusercontent.com/nakzoo/excursion/main/index.html -O /var/log/index.html; sleep 15; done"]
    volumeMounts:
    - name: sharedvolume
      mountPath: /var/log/

  volumes:
  - name: sharedvolume
    emptyDir: {}
