apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  annotations:
    owner: "Bayram OZKAN"
    notification-email: "admin@k8s.fundamentals.com"
    releasedata: "13.08.2024"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    resources:
    ports:
    - containerPort: 80
