apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-production-rb
  namespace: production # namespace adı
subjects:
- kind: Group
  name: junior    # Grubun adı
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view      # ne yetkisi olacak -> sadece okuma
  apiGroup: rbac.authorization.k8s.io  
