apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-test-rb
  namespace: test # namespace adı
subjects:
- kind: Group
  name: junior    # Grubun adı
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit      # ne yetkisi olacak - oluşturma ve silme
  apiGroup: rbac.authorization.k8s.io
