apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sr-production-rb
  namespace: production # namespace adı
subjects:
- kind: Group
  name: senior    # Grubun adı
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit      # ne yetkisi olacak -> sadece okuma
  apiGroup: rbac.authorization.k8s.io  
