apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sr-test-rb
  namespace: test # namespace adı
subjects:
- kind: Group
  name: test    # Grubun adı
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit      # ne yetkisi olacak
  apiGroup: rbac.authorization.k8s.io  
