apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque

#Verilerimi 2 türlü girebiliriz (data ve stringData)

data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}

# stringData:
#   db_server: db.example.com
#   db_username: admin
#   db_password: P@ssw0rd!
